version: 2

models:
    - name: condition
      description: Diagnosis list
      config:
        schema: "{{ var('data_set')}}_core"
      tests:
         - unique:
             column_name: "(encounter_id || patient_id || condition_date || code || diagnosis_rank || present_on_admit)"
      columns:
        - name: patient_id
          description: unique identifier