version: 2

models:
    - name: encounter
      description: Encounter details
      config:
        schema: "{{ var('data_set')}}_core"
      columns:
        - name: encounter_id
          description: Unique identifier
          tests:
            - unique
            - not_null
        - name: patient_id  
          description: unique identifier