version: 2

models:
    - name: medical_claim_stage
      description: Claim line level detail
      config:
        schema: "{{ var('data_set')}}_claims_preprocessing"
      tests:
         - unique:
             column_name: "(claim_id || claim_line_number)"
      columns:
        - name: patient_id  
          description: unique identifier